sudo: false
language: node_js
node_js:
- 0.1
- 0.12
- 4
before_script:
- npm install -g eslint eslint-config-mourner
script:
- eslint --fix src/app.js && echo 'fix lint :)'
- npm run lint && echo 'run lint :)'
- npm run build && echo 'run build :)'
- npm run build-min && echo 'run build min :)'
deploy:
  skip_cleanup: true
  provider: npm
  email: robyremzy@openmailbox.org
  on:
    tags: true
    repo: RobyRemzy/cozy-map
    branch: master
  api_key:
    secure: ddnJJUN7tfWh9lS4Uho1UtX2VKTzF1SAOlO+wi33MOtwuY2bIjRG9NCvW0aOZ8RB89gFKfxmqbEvSVOENcaT9WP4CVl7JVK7FuaIojBHdqe3iMtyVXpQ6Hb7w6GDEUKl2XaTdfK7AbDcZfQM1oE0oiRu2eLoBMFG90mOj9lIm9twyHqky2RZ2gxuDSvStRWpBQzc49SCdqWnwBt9d+UazbjYjQV/B7Db5bvbkImuduh5Odb4eNa9KpcgwgTj8ONCjjF6exDm8OQKJ/eYwTz5nDbW1jkyrLKXUv65ut0UiE5iNSuwqum7fNhQVKwSXHSdf0e25oyN3IRSfdGWjkJ1BDQhKTWEsNPE9ObKqeQ5AtsAB9wi39UEkJu6u4gHoFxVf8/wfnzFJfBKFO8PpR/SOZszYO6kiNr5fJlqfySfxWUBhTjElteironQSWuLSIdD1uaylZIk1xgEvfhZ+9gMvNJ0ZcksPRu5zZUIM4ohLpTdpB3aJa8xW5IjTeTvjtTJi1b/ahYgMizqOGjTF7qiOrpjZsNZwyX4HLAZB6+9OmWpSwfkGnCO8+cKQ0SDzbeBqTxNcSdbkULs58Ih9PiD5JMAY3emFqVcC2+774F7HC9i5K5MshenTI4vODYYDaPxshMpQm8kPun++Lq29O+CE1V7b0t+dgitAvf73eVdr58=
after_deploy: echo 'deployed :)'
notifications:
  email: false
  irc: chat.freenode.net#robydev
